name: db-mining
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.*
  - git=2.23.*
  - jupyter=1.0.*
  - matplotlib=3.1.*
  - openpyxl=2.6.*
  - pandas=0.25.*
  - requests=2.22.*
  - xlrd=1.2.*
  - sqlalchemy=1.3.*
  - flask=1.1.*
  - flask-sqlalchemy=2.4.*
  - flask-cors=3.0.*
  - nodejs=12.8.*
  - ansi2html=1.5.*